In [1]:
import torch
from pssolver import SpectralSolver

pygame 2.6.1 (SDL 2.28.4, Python 3.13.2)
Hello from the pygame community. https://www.pygame.org/contribute.html


ERROR: Could not find a version that satisfies the requirement pssolver (from versions: none)
ERROR: No matching distribution found for pssolver


In [9]:
class ZeroModel(torch.nn.Module):
    def forward(self, fields):
        return 0
nlmodel = ZeroModel()

In [10]:
c = torch.randn(5,5)
a =torch.ones(1,1)
a,c

(tensor([[1.]]),
 tensor([[-1.7874e+00,  6.7377e-01,  5.1431e-01,  7.2913e-01,  3.1684e-01],
         [ 2.6778e-01,  1.0236e+00,  7.1265e-01,  1.6832e+00, -2.1930e-01],
         [ 1.3228e-01,  4.1002e-01, -4.7121e-01,  1.3746e-01, -1.8952e+00],
         [ 1.0968e+00,  2.7014e-01, -5.5755e-01, -1.4333e+00, -1.5772e+00],
         [-2.6651e-01,  4.7450e-01, -4.6812e-01,  3.5337e-01, -9.0911e-04]]))

In [11]:
a-c

tensor([[ 2.7874,  0.3262,  0.4857,  0.2709,  0.6832],
        [ 0.7322, -0.0236,  0.2874, -0.6832,  1.2193],
        [ 0.8677,  0.5900,  1.4712,  0.8625,  2.8952],
        [-0.0968,  0.7299,  1.5575,  2.4333,  2.5772],
        [ 1.2665,  0.5255,  1.4681,  0.6466,  1.0009]])

In [16]:
a = torch.ones(3,5,5)
b = torch.randn(5,5)
c = torch.randn(5,5)
d = torch.cat([a, b.unsqueeze(0), c.unsqueeze(0)])
b,c,d

(tensor([[ 0.1600,  0.6155, -0.4140,  2.4709,  0.9220],
         [-0.6957,  2.1604, -0.3642,  1.1321,  1.5112],
         [-0.5051, -0.2130,  0.2403, -0.6395,  0.1599],
         [-0.8898, -0.2859,  0.4596,  0.4518, -0.1382],
         [-0.8277, -0.8328,  0.6524, -0.4613, -0.4314]]),
 tensor([[ 0.7958, -0.0105, -0.7889, -1.1067, -0.4418],
         [ 0.2745,  0.3832, -1.0990, -0.3047,  0.3937],
         [ 0.3272, -1.4132, -0.8062, -0.7564, -0.7398],
         [ 0.4808, -1.3227,  0.2973,  1.4978,  0.5296],
         [-1.2017, -0.2959, -1.3813, -1.0704,  0.4249]]),
 tensor([[[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000]],
 
         [[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 1.0000,  1.0000,  1.00

In [ ]:
a = torch.stack([torch.ones(10,10)])
a.shape

torch.Size([1, 10, 10])

In [7]:
a + torch.stack([torch.ones(10,10),torch.zeros(10,10)])

tensor([[[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.,

In [2]:
N = 128
L = 128
dt = 0.1
steps = 100000
device = 'cuda' if torch.cuda.is_available() else 'cpu'

solver = System(shape = (N,N), L=L, dt=dt, device=device, record_every_n_steps = steps/100)


In [3]:

def init_u(N):
    u = torch.ones(N, N)
    r = 10  # half size of perturbation square
    u[N//2 - r:N//2 + r, N//2 - r:N//2 + r] = 0.50
    u += 0.02 * torch.randn(N, N)
    return u

def init_v(N):
    v = torch.zeros(N, N)
    r = 10
    v[N//2 - r:N//2 + r, N//2 - r:N//2 + r] = 0.25
    v += 0.02 * torch.randn(N, N)
    return v


In [4]:

# # --- Parameters ---
du = 0.16
dv = 0.08
F = 0.06
k = 0.062

# --- Add active fields ---
solver.model.add_dynamic_field(
    "u",
    init = init_u(N),
    L_hat = -solver.q2 * (du),
    N_hat = lambda R: torch.fft.fft2(-R["u"] * R["v"]**2 + F * (1 - R["u"]))
)
# --- Add active fields ---
solver.model.add_dynamic_field(
    "v",
    init =  init_v(N),
    L_hat = -solver.q2 * (dv),
    N_hat = lambda R: torch.fft.fft2(R["u"] * R["v"]**2 - (F + k) * R["v"])
)


In [5]:
solver.model.fields.name_to_idx

{'u': 0, 'v': 1}

In [6]:
solver.model.fields['u'].shape
# plt.imshow(solver.model.fields['u'].cpu().numpy())

torch.Size([128, 128])

In [7]:
# solver.run(1)
# print('ran once')

In [8]:
# solver.model.fields['u']

In [7]:
import time 

traj = []
start = time.time()
for i in range(steps):
    solver.run(1)
    if i % solver.record_every_n_steps == 0:
        traj.append(solver.model.fields['u'])
end = time.time()
print(f"Elapsed time: {end - start:.6f} seconds")
traj = torch.stack(traj)

Elapsed time: 10.871623 seconds


In [ ]:
from IPython.display import HTML

import matplotlib.pyplot as plt
import matplotlib.animation as animation

%matplotlib inline


fig, ax = plt.subplots()
im = ax.imshow(traj[0].detach().cpu().numpy(), cmap='viridis', origin='lower', animated=True)
ax.set_title("PseudoSpectralSolver2D Evolution")
cbar = fig.colorbar(im, ax=ax)
cbar.set_label("Field Value")

def update(frame):
    im.set_array(traj[frame].detach().cpu().numpy())
    ax.set_xlabel(f"Step {frame}")
    im.set_clim(vmin=traj[frame].min().cpu().item(), vmax=traj[frame].max().cpu().item())
    cbar.update_normal(im)
    return [im]

ani = animation.FuncAnimation(fig, update, frames=traj.shape[0], blit=True, interval=50)
plt.close(fig)  # Prevents duplicate static plot
display(HTML(ani.to_jshtml()))
print(traj.shape)

In [11]:
data = torch.randn(5, 128, 128)

In [12]:
data_fft = torch.fft.fft2(data)

In [13]:
data_fft.shape

torch.Size([5, 128, 128])

In [14]:
(0,)+(1,2)

(0, 1, 2)

In [9]:
data = torch.randn(5, 128, 128, device = 'cuda')

In [12]:
data.fft2()

AttributeError: 'Tensor' object has no attribute 'fft2'

In [17]:
a  = torch.stack([i for i in data], dim = 0)
a.shape

torch.Size([5, 128, 128])

In [18]:
data[0].shape

torch.Size([128, 128])

In [19]:
data[[0,3,4]] = torch.zeros_like(data[[0,3,4]]) 

In [20]:
data

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         ...,
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00]],

        [[ 3.1043e-01,  2.9380e-01,  6.2636e-01,  ..., -8.2809e-01,
           1.0208e+00, -5.9163e-01],
         [-1.1424e+00, -1.6972e+00, -4.9643e-01,  ..., -4.8535e-01,
          -5.9452e-01, -6.3947e-01],
         [ 8.1869e-01, -4.9249e-01, -7.9414e-01,  ...,  7.0070e-01,
           3.4647e-01,  1.1032e+00],
         ...,
         [ 5.8970e-01,  6

In [21]:
a = torch.zeros( (0,) + (10,10) )

In [22]:
torch.zeros_like(a[:1])

tensor([], size=(0, 10, 10))